### ISSUE TITLE
Could not get this adapter working via the example, without an existing policy to load

### ISSUE THREAD

**Issue by sgtsquiggs** [casbin/json-adapter#4]
I am using this adapter to essentially have an in-memory policy. I was unable to continue without pre-seeding the byte buffer with `[]`:

```go
func (a *Adapter) loadFromBuffer() error {
	var policy []CasbinRule
	err := json.Unmarshal(*a.source, &policy)
	if err == nil {
		a.policy = policy
	}
	return err
}
```
err is `unexpected end of JSON input` which is expected given the code.

**Comment by yyy1000** [comment]
> I am using this adapter to essentially have an in-memory policy. I was unable to continue without pre-seeding the byte buffer with `[]`:
> 
> ```go
> func (a *Adapter) loadFromBuffer() error {
> 	var policy []CasbinRule
> 	err := json.Unmarshal(*a.source, &policy)
> 	if err == nil {
> 		a.policy = policy
> 	}
> 	return err
> }
> ```
> 
> err is `unexpected end of JSON input` which is expected given the code.

Do you mean you can't run the example in README?
That is because 
`b := []byte{} // b stores Casbin policy in JSON bytes.`  needs to initialize  []byte.
You could use 
`b, _ := ioutil.ReadFile(filepath.Join("examples", "rbac_policy.json"))` to do that.

**Comment by hsluoyz** [comment]
@sgtsquiggs can you give a full example of your code?

**Comment by sgtsquiggs** [comment]
```go
func TestCasbinEnforcerWithInMemoryStoreAndNoSeededPolicy(t *testing.T) {
	modelStr := `
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && r.act == p.act
`
	model, err := casbinModel.NewModelFromString(modelStr)
	if err != nil {
		t.Fatalf("failed to load model: %v", err)
	}

	var buf []byte
	adapter := jsonadapter.NewAdapter(&buf)

	enforcer, err := casbin.NewEnforcer(model, adapter)
	if err != nil {
		t.Fatalf("failed to initialize enforcer: %v", err)
	}

	ok, err := enforcer.AddPolicy("some_user", "some_scope", "some_permission")
	if err != nil {
		t.Fatalf("failed to add policy: %v", err)
	}

	if !ok {
		t.Error("policy was not added?")
	}
}
```

results with

```
=== RUN   TestCasbinEnforcerWithInMemoryStoreAndNoSeededPolicy
    casbin_test.go:43: failed to initialize enforcer: unexpected end of JSON input
--- FAIL: TestCasbinEnforcerWithInMemoryStoreAndNoSeededPolicy (0.00s)
```

**Comment by sgtsquiggs** [comment]
I think this falls under "who's responsible for creating the database?" - if it's me, then I can just seed the json adapter with `[]` and we're done.

**Comment by sgtsquiggs** [comment]
Additionally - I just wanted an in-memory-only enforcer. It just occurred to me that I can omit an adapter entirely without using this json adapter. I chose this adapter bc it was the closest to "in memory" from the adapter list.

**Comment by yyy1000** [comment]
I'm not sure I got your idea totally.
But I think you could try [String Adapter](https://github.com/qiangmzsx/string-adapter), this may satisfy your needs.

**Comment by yyy1000** [comment]
> Additionally - I just wanted an in-memory-only enforcer. It just occurred to me that I can omit an adapter entirely without using this json adapter. I chose this adapter bc it was the closest to "in memory" from the adapter list.

Hi, https://github.com/casbin/json-adapter/pull/5 could solve your problem when creating an in-memory adapter with an empty []byte.
