### ISSUE TITLE
Update the installation docs

### ISSUE THREAD

**Issue by pooyakn** [casbin/json-adapter#8]
If you install the adapter using the command ```go get github.com/casbin/json-adapter```, it's not compatible with the latest casbin v2. Also, the current version module name is github.com/casbin/json-adapter/v2. The installation guide should be updated to ```go get github.com/casbin/json-adapter/v2```.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/json-adapter/commit/65905f21a62a0c89ed1701729bc3d47334b544a6
